apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  labels:
    app: {{ .Values.image.name }}
spec:
  selector:
    app: {{ .Values.image.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.containerPort }}
  type: NodePort