replicaCount: 3

containerPort: 8080
port: 80

servicetype: NodePort
image:
  name: go-web-app
  repository: subratdevops/go-web-app
  tag: stable

resources:
  requests:
    cpu: "300m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
